### ISSUE TITLE
Using /functions convention

### ISSUE THREAD

**Issue by lmaccherone** [lukeed/pages-fullstack#3]
This may be an issue for the sveltekit cloudflare adapter team but I'm wondering why this doesn't use the `/functions` convention for deploying to pages? In looking at the generated code, it's not actually clear to me how server-side functionality like the `/todos.json` endpoint is accomplished. Is it all in the `_workers.js` file?

**Comment by lukeed** [comment]
Hey, the adapter doesn't use the `/functions` approach because then you wouldn't be using SvelteKit. When using `/functions`, Pages applies its own framework-like build system, wiring up file paths and any `onRequest*` handlers to route handlers. There's no window into that build process that would allow SvelteKit to scooch in & do what it needs to do. Plus, SvelteKit has no idea what `onRequest` or any of the other exports are & mean.

The idea of adapters is to build SK apps the same way using all the same features across all platforms. This means you only have to learn 1 framework instead of N adapter-variant frameworks.

If you're suggesting that the SK adapter should _produce_ a `/functions` directory, this still doesn't make a ton of sense. Pages, during build time, zips up all the `/functions` contents & produces a single Worker from those files anyway. So the adapter would have to augment SK's entire build pipeline (which is already expecting to handle everything start-to-finish, producing a single output) so that it can place things in a more delicate arrangement. It's a lot of extra work & moving pieces for the same result.

FWIW, Pages [encourages frameworks to use `_worker.js` for their output target](https://developers.cloudflare.com/pages/platform/functions#advanced-mode).

Hope that helps~!

**Comment by lmaccherone** [comment]
It does. Thanks!

The one question I have is around the efficiency of serving static assets. I assume that they use Cloudflare's CDN when served from a traditional pages approach. Using _worker.js, the worker itself has to serve static assets so I'm wondering if that inefficiency is significant. I also like the idea of middleware and sveltekit lacks that at the moment so I'm considering switching my app to a plain svelte SPA and using Cloudflare's native functionality.

**Comment by lukeed** [comment]
Pages, by default, attempts to match/reply with a static asset first & foremost. This is still the case when using the `/functions` hierarchy. It's the same as if there were no `/functions` at all.

When defining a `_worker.js` file, the _entire_ behavior (including asset-lookup method, timing, etc) is up to you, the `_worker.js` author. The SK-generated output knows exactly what assets it produced, so SK relies on its own manifest to determine "should we look for an asset or do something SSR-related?". It's technically a little more efficient, but is hardly worth mentioning. We (SK) did it in this order because we already have all the manifest information at our disposal. Most other frameworks don't/won't, so checking `env.ASSETS.fetch` _before_ any SSR-related behavior would be a fine approach too.
