### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by PH4NTOMiki** [lukeed/pages-fullstack#5]
Hello @lukeed how are you supposed to access environmental variables during runtime, I tried both ```process.env.ENV_NAME``` and just ```ENV_NAME``` and they both don't work, can you help me

Thanks

**Comment by lukeed** [comment]
If you are passing ENV variables into your build, then define them in the Pages settings (both environments) and access them within your `svelte.config.js`, for example.

If you are trying to define ENV variables for your client to access at run-time, then you have to rely on SvelteKit docs for how to do this. The TLDR is that SK relies on Vite, which means you have to define ENVs the way Vite expects: the variable name must have `VITE_` prefix; see [here](https://vitejs.dev/guide/env-and-mode.html)

This means you define something like `VITE_ENV_NAME` in your Pages settings (instead of using `.env` files) and then your runtime code uses that value via `import.meta.env.VITE_ENV_NAME`.

**Comment by pheuter** [comment]
@lukeed How about server env vars? During local dev, I can access them using `process.env.ENV_NAME`, but not clear how to access them once deployed to Cloudflare Pages. 

Note that you don't want to prefix server env vars with `VITE_` and access using `import.meta.env` because they're supposed to be secret and not be accessible by built client assets.
